from typing import List, Optional
from pydantic import BaseModel, Field

class ProvenanceCitation(BaseModel):
    """A specific spatial citation pointing back to the source document."""
    document_name: str
    document_id: str
    page_number: int
    bbox: Optional[list] = None # Or use the BoundingBox model
    content_hash: str

class ProvenanceChain(BaseModel):
    """Audit trail attached to any Answer generated by the Query Agent."""
    citations: List[ProvenanceCitation] = Field(default_factory=list)
    verification_status: str = "unverified" 

class PageIndexNode(BaseModel):
    """A node in the hierarchical section tree representing the document's structure."""
    section_title: str
    page_start: int
    page_end: int
    summary: str = ""
    key_entities: List[str] = Field(default_factory=list)
    data_types_present: List[str] = Field(default_factory=list)
    child_sections: List['PageIndexNode'] = Field(default_factory=list)

class PageIndex(BaseModel):
    """The root of the tree representing the entire document's Smart TOC."""
    document_id: str
    root_node: PageIndexNode
