from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, model_validator

from src.models.extraction import BoundingBox


class VerificationStatus(str, Enum):
    UNVERIFIED = "unverified"
    VERIFIED = "verified"
    NEEDS_REVIEW = "needs_review"


class ProvenanceCitation(BaseModel):
    """A specific document citation used inside a provenance chain."""

    document_name: str = Field(..., min_length=1)
    document_id: str = Field(..., min_length=1)
    page_number: int = Field(..., ge=1)
    excerpt: Optional[str] = Field(default=None, min_length=1)
    bbox: Optional[BoundingBox] = None


class ProvenanceChain(BaseModel):
    """Audit trail attached to any answer generated by the Query Agent."""

    document_name: str = Field(..., min_length=1)
    page_number: int = Field(..., ge=1)
    citations: List[ProvenanceCitation] = Field(default_factory=list)
    bbox: Optional[BoundingBox] = None
    content_hash: str = Field(..., min_length=16, description="Stable hash of the traced content")
    verification_status: VerificationStatus = VerificationStatus.UNVERIFIED

    @model_validator(mode="after")
    def validate_verified_chain(self) -> "ProvenanceChain":
        if self.verification_status == VerificationStatus.VERIFIED and not self.citations:
            raise ValueError("verified provenance chain must include at least one citation")
        if self.citations:
            first = self.citations[0]
            if first.document_name != self.document_name:
                raise ValueError("document_name must align with first citation")
            if first.page_number != self.page_number:
                raise ValueError("page_number must align with first citation")
        return self


class PageIndexNode(BaseModel):
    """A node in the hierarchical section tree representing the document structure."""

    section_title: str = Field(..., min_length=1)
    page_start: int = Field(..., ge=1)
    page_end: int = Field(..., ge=1)
    summary: str = ""
    key_entities: List[str] = Field(default_factory=list)
    data_types_present: List[str] = Field(default_factory=list)
    child_sections: List["PageIndexNode"] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_page_range(self) -> "PageIndexNode":
        if self.page_end < self.page_start:
            raise ValueError("page_end must be greater than or equal to page_start")
        for child in self.child_sections:
            if child.page_start < self.page_start or child.page_end > self.page_end:
                raise ValueError("child section page range must be contained within parent page range")
        return self


class PageIndex(BaseModel):
    """The root object representing the document Smart TOC."""

    document_id: str = Field(..., min_length=1)
    root_node: PageIndexNode
